const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const HTTP_STATUS_MESSAGES = {
  OK: "Success",
  CREATED: "Resource created successfully",
  BAD_REQUEST: "Bad request",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Resource not found",
  CONFLICT: "Resource conflict",
  INTERNAL_SERVER_ERROR: "Internal server error",
};

const TICKET_STATUS = {
  CONFIRMED: "CONFIRMED",
  RAC: "RAC",
  WAITING: "WAITING",
  CANCELLED: "CANCELLED",
};

const BERTH_TYPES = {
  LOWER: "LOWER",
  MIDDLE: "MIDDLE",
  UPPER: "UPPER",
  SIDE_LOWER: "SIDE_LOWER",
};

const BERTH_STATUS = {
  AVAILABLE: "AVAILABLE",
  CONFIRMED: "CONFIRMED",
  RAC: "RAC",
  WAITING: "WAITING",
};

const TICKET_LIMITS = {
  TOTAL_CONFIRMED_BERTHS: 63,
  TOTAL_RAC_BERTHS: 9,
  TOTAL_RAC_TICKETS: 18,
  MAX_WAITING_LIST: 10,
  CHILD_AGE_LIMIT: 5,
  SENIOR_CITIZEN_AGE: 60,
};

const BERTH_PRIORITY = {
  SENIOR_CITIZEN: 1,
  WOMEN_WITH_CHILDREN: 2,
  REGULAR: 3,
};

module.exports = {
  HTTP_STATUS_CODES,
  HTTP_STATUS_MESSAGES,
  TICKET_STATUS,
  BERTH_TYPES,
  BERTH_STATUS,
  TICKET_LIMITS,
  BERTH_PRIORITY,
};
